apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-web-app
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  source:
    repoURL: "https://github.com/omnagare9975/k8s-argo-cd-assignment.git"
    path: kubernetes/manifests
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

